#端口号
server:
  port: 8090
spring:
  application:
    name: pda
  #设置数据源
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/pda?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8&characterSetResults=UTF-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  #redis数据库配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    auth: 123456
#sql版本控制
liquibase:
  change-log: classpath:/sql/master.xml
  enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:pageInterceptor/page-Interceptor.xml