#端口号
server:
  port: 8080
spring:
  application:
    name: pda
  #设置数据源
  datasource:
    druid:
      #url: jdbc:mysql://122.51.17.153:3306/pda?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8&characterSetResults=UTF-8
      url: jdbc:mysql://localhost:3306/pda?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8&characterSetResults=UTF-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  #redis数据库配置
  redis:
    database: 0
    #host: 122.51.17.153
    host: 127.0.0.1
    port: 6379
    password: 123456
#sql版本控制
liquibase:
  change-log: classpath:/sql/master.xml
  enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
#是否展示swagger接口
swagger:
  enable: true